### ISSUE TITLE
Considering porting these changes over to Bright Brights

### ISSUE THREAD

**Issue by chaosvolt** [ERRORCODE509/crack_the_nut#1]
Having seen the resulting memery that's come about due to all this talk of nutcracking on reddit, I realized this would be a sensible change to port over to the Bright Nights fork.

Figured I'd ask your thoughts on that, even though it's a simple enough change that asking permission probably isn't strictly necessary, but mentioning your implementation as the inspiration would still be warranted. Plus I can see "BN has better nutcracking than DDA" this adding to the amusement this discussion has already generated on the CDDA subreddit.

I'll be out and about today, so if someone else hasn't tackled the idea by the time I get home I'll get cracking (pun intended) and open a quick PR once I do.

**Comment by ERRORCODE509** [comment]
Yeah, go right ahead. It feels like a bit of an honor to have one of my mods included in BN.

**Comment by chaosvolt** [comment]
Sent up a PR here: https://github.com/cataclysmbnteam/Cataclysm-BN/pull/599

Main difference is I went with changing the time of BN's currently-existing uncrafts, rather than re-implementing the old recipes that got obsoleted, but listed recipe revivals and/or tweaks among the possible alternatives.

**Comment by ERRORCODE509** [comment]
Yeah, I was a bit lazy when I made this and just added crafting recipes rather than disassembly recipes. It was done purely because it was easier.

**Comment by chaosvolt** [comment]
And the PR is merged. The PR discussion led in an interesting direction thanks to Coolthulhu's feedback. In short, needing to crack nuts in the first place ended up getting, you could say, realism'd out. XP
